// Package rudirect implements the "Russian sites directly" split-tunnel policy.
//
// Traffic to Russian networks (IPv4 prefixes in data/ru-direct-v4.txt) leaves the
// device through the physical uplink instead of the VPN tunnel, so Russian
// services see the user's real Russian address. Everything else keeps using
// the tunnel. DNS queries for Russian domains (IsRussianDomain) are resolved by
// a Russian resolver directly so that geo-aware CDNs return Russian edges.
//
// The dataset is generated by tools/ru-direct/gen.py and shared with the
// Android client (it is packaged as an APK asset).
package rudirect

import (
	"bufio"
	_ "embed"
	"encoding/binary"
	"errors"
	"net/netip"
	"sort"
	"strings"
	"sync"
)

//go:embed data/ru-direct-v4.txt
var directList string

//go:embed data/ru-direct-complement.txt
var complementList string

var (
	once   sync.Once
	direct []netip.Prefix
	comp   []netip.Prefix
	ranges []span
)

type span struct{ lo, hi uint32 }

func parse(src string) []netip.Prefix {
	var out []netip.Prefix
	sc := bufio.NewScanner(strings.NewReader(src))
	for sc.Scan() {
		line := strings.TrimSpace(sc.Text())
		if line == "" || strings.HasPrefix(line, "#") {
			continue
		}
		p, err := netip.ParsePrefix(line)
		if err != nil || !p.Addr().Is4() {
			continue
		}
		out = append(out, p.Masked())
	}
	return out
}

func load() {
	once.Do(func() {
		direct = parse(directList)
		comp = parse(complementList)
		ranges = make([]span, 0, len(direct))
		for _, p := range direct {
			b := p.Addr().As4()
			lo := binary.BigEndian.Uint32(b[:])
			hi := lo | (^uint32(0) >> uint(p.Bits()))
			if p.Bits() == 0 {
				hi = ^uint32(0)
			}
			ranges = append(ranges, span{lo, hi})
		}
		sort.Slice(ranges, func(i, j int) bool { return ranges[i].lo < ranges[j].lo })
	})
}

// Prefixes returns the IPv4 prefixes that must bypass the tunnel. The slice
// must not be modified.
func Prefixes() []netip.Prefix { load(); return direct }

// TunnelPrefixes returns the complement list: the prefixes that must be routed
// into the tunnel on platforms that cannot express route exclusions
// (Android < 13). It covers all public IPv4 space except Russian networks.
func TunnelPrefixes() []netip.Prefix { load(); return comp }

// Contains reports whether addr belongs to the direct (Russian) set.
func Contains(addr netip.Addr) bool {
	load()
	addr = addr.Unmap()
	if !addr.Is4() {
		return false
	}
	b := addr.As4()
	v := binary.BigEndian.Uint32(b[:])
	i := sort.Search(len(ranges), func(i int) bool { return ranges[i].lo > v })
	return i > 0 && v <= ranges[i-1].hi
}

// Russian top-level domains (IDN TLDs in punycode).
var ruTLDs = []string{"ru", "su", "xn--p1ai", "xn--d1acj3b", "xn--80adxhks", "xn--80asehdb", "xn--c1avg", "moscow", "tatar", "yandex"}

// Russian services hosted under generic TLDs. Matching includes subdomains.
var ruDomains = []string{
	// Yandex
	"yandex.com", "yandex.net", "yastatic.net", "yandex.st", "ya.cc", "yandexcloud.net", "yandex.cloud", "kinopoisk.tv",
	// VK / Mail.ru group
	"vk.com", "vk.me", "vk.cc", "vk.link", "vkontakte.com", "userapi.com", "vkuser.net", "vk-cdn.net", "vkuseraudio.net", "vkuservideo.net",
	"vk-portal.net", "mycdn.me", "ok.me", "odnoklassniki.com", "imgsmail.net", "mradx.net", "vkpay.io", "vkplay.com", "vkvideo.com", "max.me",
	// banks, payments, government
	"sber.com", "sberbank.com", "sberdevices.com", "tinkoff.com", "tbank.com", "tcsbank.com", "nspk.com", "mironline.com",
	// marketplaces, classifieds, delivery
	"ozon.com", "ozone.com", "wildberries.com", "wb.com", "wbbasket.com", "wbstatic.net", "avito.st", "avito.com", "cdek.com", "samokat.com",
	// media, maps, other
	"habr.com", "habrastorage.org", "2gis.com", "2gis.com.cy", "hh.com", "rutube.com", "ivi.tv", "okko.tv", "start.film", "wink.com",
	"kaspersky.com", "kaspersky-labs.com", "drweb.com", "1c.com", "qiwi.com", "rbc.com", "tass.com", "rt.com", "dzen.com",
}

var domainSet = func() map[string]struct{} {
	m := make(map[string]struct{}, len(ruDomains))
	for _, d := range ruDomains {
		m[d] = struct{}{}
	}
	return m
}()

// IsRussianDomain reports whether a DNS name belongs to a Russian TLD or to a
// curated list of Russian services hosted under generic TLDs.
func IsRussianDomain(name string) bool {
	name = strings.ToLower(strings.TrimSuffix(strings.TrimSpace(name), "."))
	if name == "" {
		return false
	}
	tld := name
	if i := strings.LastIndexByte(name, '.'); i >= 0 {
		tld = name[i+1:]
	}
	for _, t := range ruTLDs {
		if tld == t {
			return true
		}
	}
	for s := name; ; {
		if _, ok := domainSet[s]; ok {
			return true
		}
		i := strings.IndexByte(s, '.')
		if i < 0 {
			return false
		}
		s = s[i+1:]
	}
}

var errMalformed = errors.New("rudirect: malformed DNS message")

// QuestionName extracts the first question name from a wire-format DNS
// message (without TCP length prefix).
func QuestionName(msg []byte) (string, error) {
	if len(msg) < 12 || binary.BigEndian.Uint16(msg[4:6]) == 0 {
		return "", errMalformed
	}
	var sb strings.Builder
	for off := 12; ; {
		if off >= len(msg) {
			return "", errMalformed
		}
		l := int(msg[off])
		if l == 0 {
			break
		}
		if l&0xC0 != 0 || off+1+l > len(msg) || sb.Len()+l > 254 {
			return "", errMalformed
		}
		if sb.Len() > 0 {
			sb.WriteByte('.')
		}
		sb.Write(msg[off+1 : off+1+l])
		off += 1 + l
	}
	return sb.String(), nil
}
