//go:build linux
package main
import("time";"bytes";"crypto/sha256";"encoding/hex";"encoding/json";"io";"net/http";"net/http/httptest";"os";"path/filepath";"strings";"testing")
func testWebsite(t *testing.T)*website{t.Helper();dir:=t.TempDir();return &website{dir:dir,statePath:filepath.Join(dir,"statistics.json"),manifestPath:filepath.Join(dir,"manifest.json"),salt:[]byte("private-test-salt-never-a-production-credential"),monitor:[]byte("test-monitor-only"),stats:statistics{Version:1,Days:map[string]*daily{}}}}
func TestPrivateCountersAndRangeDownloads(t *testing.T){s:=testWebsite(t);body:=[]byte("release-fixture-data");file:="fixture.apk";if e:=os.WriteFile(filepath.Join(s.dir,file),body,0644);e!=nil{t.Fatal(e)};sum:=sha256.Sum256(body);s.manifest=manifest{Version:1,Assets:[]releaseAsset{{ID:"android",File:file,Size:int64(len(body)),SHA256:hex.EncodeToString(sum[:])}}};handler:=s.handler();r:=httptest.NewRequest("GET","/vpn/",nil);r.RemoteAddr="203.0.113.42:9876";handler.ServeHTTP(httptest.NewRecorder(),r);r=httptest.NewRequest("HEAD","/vpn/download/android",nil);r.RemoteAddr="203.0.113.42:9876";handler.ServeHTTP(httptest.NewRecorder(),r);r=httptest.NewRequest("GET","/vpn/download/android",nil);r.RemoteAddr="203.0.113.42:9876";r.Header.Set("Range","bytes=0-3");w:=httptest.NewRecorder();handler.ServeHTTP(w,r);if w.Code!=206||w.Body.Len()!=4{t.Fatal("range failed",w.Code,w.Body.Len())};r=httptest.NewRequest("GET","/vpn/download/android",nil);r.RemoteAddr="203.0.113.42:9876";w=httptest.NewRecorder();handler.ServeHTTP(w,r);if w.Code!=200||!bytes.Equal(w.Body.Bytes(),body){t.Fatal("full download failed")};if e:=s.persist();e!=nil{t.Fatal(e)};b,_:=os.ReadFile(s.statePath);if bytes.Contains(b,[]byte("203.0.113.42")){t.Fatal("raw IP persisted")};for _,d:=range s.stats.Days{if d.PageViews!=1||d.DownloadRequests!=2||d.RangeRequests!=1||d.CompletedFull!=1||d.Unique!=1{t.Fatal("counter semantics",d)}}}
func TestManifestIntegrityAndTraversal(t *testing.T){s:=testWebsite(t);m:=manifest{Version:1,Assets:[]releaseAsset{{ID:"android",File:"../../secret",Size:1,SHA256:strings.Repeat("a",64)}}};b,_:=json.Marshal(m);_=os.WriteFile(s.manifestPath,b,0600);if s.loadManifest()==nil{t.Fatal("manifest traversal accepted")};w:=httptest.NewRecorder();s.download(w,httptest.NewRequest("GET","/vpn/download/../../secret",nil));if w.Code!=404{t.Fatal("download traversal accepted")}}
type fakeTransport func(*http.Request)(*http.Response,error)
func(f fakeTransport)RoundTrip(r *http.Request)(*http.Response,error){return f(r)}
func TestActivationFixedDestinationNoCredentialForwarding(t *testing.T){s:=testWebsite(t);s.backendURL="https://203.0.113.10:51843";called:=false;s.client=&http.Client{Transport:fakeTransport(func(r *http.Request)(*http.Response,error){called=true;if r.URL.String()!="https://203.0.113.10:51843/vpn-api/v1/enroll"||r.Header.Get("Cookie")!=""||r.Header.Get("Authorization")!=""{t.Fatal("unsafe proxy",r.URL,r.Header)};return &http.Response{StatusCode:200,Header:http.Header{"Content-Type":[]string{"application/json"}},Body:io.NopCloser(strings.NewReader(`{"ok":true}`))},nil})};r:=httptest.NewRequest("POST","/vpn/api/v1/enroll",strings.NewReader(`{}`));r.Header.Set("Origin",publicOrigin);r.Header.Set("Content-Type","application/json");r.Header.Set("Cookie","unrelated-cookie");r.Header.Set("Authorization","Bearer unrelated-secret");w:=httptest.NewRecorder();s.proxyActivation(w,r);if w.Code!=200||!called{t.Fatal(w.Code,w.Body.String())};r=httptest.NewRequest("POST","/vpn/api/v1/enroll",strings.NewReader(`{}`));r.Header.Set("Origin","https://evil.invalid");r.Header.Set("Content-Type","application/json");w=httptest.NewRecorder();s.proxyActivation(w,r);if w.Code!=403{t.Fatal("cross-origin accepted")}}
func TestMonitorRequiresCredentialAndOmitsPseudonyms(t *testing.T){s:=testWebsite(t);s.record(httptest.NewRequest("GET","/vpn/",nil),true,"",200,0,0);w:=httptest.NewRecorder();s.monitorHandler(w,httptest.NewRequest("GET","/vpn/internal/monitor",nil));if w.Code!=401{t.Fatal("anonymous monitor")};r:=httptest.NewRequest("GET","/vpn/internal/monitor",nil);r.Header.Set("Authorization","Bearer "+string(s.monitor));w=httptest.NewRecorder();s.monitorHandler(w,r);if w.Code!=200||strings.Contains(w.Body.String(),`"addresses"`){t.Fatal("private visitor identifiers exposed",w.Code)}}

func TestPrivacyExpiresEvenWithoutTraffic(t *testing.T){s:=&website{stats:statistics{Version:1,Days:map[string]*daily{"2000-01-01":{PageViews:9,Unique:1,Addresses:map[string]int64{"fixture":1}}}}};s.pruneLocked(time.Now().UTC());if s.stats.Days["2000-01-01"].Addresses!=nil||s.stats.Days["2000-01-01"].PageViews!=9{t.Fatal("expired pseudonyms must disappear without deleting aggregate counts")}}
