//go:build linux
// vpn-web is a download site and a fixed, TLS-verified activation gateway.
package main
import("bytes";"context";"crypto/hmac";"crypto/sha256";"crypto/subtle";"crypto/tls";"crypto/x509";"embed";"encoding/hex";"encoding/json";"errors";"flag";"fmt";"io";"log";"net";"net/http";"os";"os/signal";"path/filepath";"regexp";"strings";"sync";"syscall";"time";"chameleon/internal/hostmetrics")
//go:embed static/*
var assets embed.FS
const publicOrigin="https://vpn.example.com"
var filename=regexp.MustCompile(`^[A-Za-z0-9][A-Za-z0-9._-]{1,120}$`)
type releaseAsset struct{ID string `json:"id"`;Platform string `json:"platform"`;Title string `json:"title"`;File string `json:"file"`;SHA256 string `json:"sha256"`;Size int64 `json:"size"`;Version string `json:"version"`;Status string `json:"status"`;Requirements string `json:"requirements"`}
type manifest struct{Version int `json:"version"`;BotURL string `json:"bot_url"`;IssuerReady bool `json:"issuer_ready"`;Assets []releaseAsset `json:"assets"`;AndroidAppID string `json:"android_app_id"`;AndroidCertSHA256 string `json:"android_cert_sha256"`}
type daily struct{PageViews uint64 `json:"page_views"`;DownloadRequests uint64 `json:"download_requests"`;CompletedFull uint64 `json:"completed_full_responses"`;RangeRequests uint64 `json:"range_requests"`;Bytes uint64 `json:"bytes_sent"`;Unique uint64 `json:"unique_addresses"`;UniqueCapped bool `json:"unique_count_capped"`;ByPlatform map[string]uint64 `json:"by_platform"`;Addresses map[string]int64 `json:"addresses,omitempty"`}
type statistics struct{Version int `json:"version"`;Days map[string]*daily `json:"days"`}
type website struct{dir,statePath,manifestPath,backendURL string;salt,monitor []byte;client *http.Client;mu sync.Mutex;stats statistics;manifest manifest;cpuTotal,cpuIdle uint64;manifestMu sync.RWMutex;manifestDigest [32]byte}
func credential(name string)([]byte,error){path:=filepath.Join(os.Getenv("CREDENTIALS_DIRECTORY"),name);b,e:=os.ReadFile(path);if e!=nil{return nil,e};b=bytes.TrimSpace(b);if len(b)<32||len(b)>256{return nil,errors.New("invalid credential size")};return b,nil}
func (s *website)loadManifest()error{b,e:=os.ReadFile(s.manifestPath);if e!=nil{return e};if len(b)>16384{return errors.New("manifest size")};digest:=sha256.Sum256(b);s.manifestMu.RLock();same:=digest==s.manifestDigest;s.manifestMu.RUnlock();if same{return nil};var m manifest;d:=json.NewDecoder(bytes.NewReader(b));d.DisallowUnknownFields();if d.Decode(&m)!=nil||m.Version!=1||len(m.Assets)>8{return errors.New("manifest invalid")};if m.BotURL!=""{if !regexp.MustCompile(`(?i)^https://t\.me/[A-Za-z0-9_]{5,32}bot$`).MatchString(m.BotURL){return errors.New("invalid bot URL")}};if m.AndroidAppID!=""&&m.AndroidAppID!="com.chameleonvpn.client"{return errors.New("unexpected app id")};seen:=map[string]bool{};for _,a:=range m.Assets{if (a.ID!="android"&&a.ID!="windows"&&a.ID!="source"&&a.ID!="dependencies")||seen[a.ID]||!filename.MatchString(a.File)||a.Size<=0||a.Size>300<<20||len(a.SHA256)!=64{return errors.New("invalid release")};seen[a.ID]=true;p:=filepath.Join(s.dir,a.File);info,e:=os.Lstat(p);if e!=nil||!info.Mode().IsRegular()||info.Size()!=a.Size||info.Mode().Perm()&0022!=0{return errors.New("release size or file missing")};f,e:=os.Open(p);if e!=nil{return e};h:=sha256.New();_,e=io.Copy(h,f);f.Close();if e!=nil||hex.EncodeToString(h.Sum(nil))!=a.SHA256{return errors.New("release checksum mismatch")}};s.manifestMu.Lock();s.manifest=m;s.manifestDigest=digest;s.manifestMu.Unlock();return nil}
func (s *website)manifestSnapshot()manifest{s.manifestMu.RLock();defer s.manifestMu.RUnlock();return s.manifest}
func (s *website)address(r *http.Request)string{ip,_,_:=net.SplitHostPort(r.RemoteAddr);if ip=="127.0.0.1"||ip=="::1"{if forwarded:=r.Header.Get("X-Real-IP");net.ParseIP(forwarded)!=nil{ip=forwarded}};return ip}
func (s *website)record(r *http.Request,page bool,id string,status int,bytes,expected int64){s.mu.Lock();defer s.mu.Unlock();day:=time.Now().UTC().Format("2006-01-02");d:=s.stats.Days[day];if d==nil{d=&daily{ByPlatform:map[string]uint64{},Addresses:map[string]int64{}};s.stats.Days[day]=d};if d.Addresses==nil{d.Addresses=map[string]int64{}};if d.ByPlatform==nil{d.ByPlatform=map[string]uint64{}};now:=time.Now().Unix();mac:=hmac.New(sha256.New,s.salt);_,_=mac.Write([]byte(day+"\n"+s.address(r)));key:=hex.EncodeToString(mac.Sum(nil));if _,ok:=d.Addresses[key];!ok{if len(d.Addresses)<20000{d.Unique++;d.Addresses[key]=now}else{d.UniqueCapped=true}}else{d.Addresses[key]=now};if page{d.PageViews++};if id!=""{d.DownloadRequests++;d.ByPlatform[id]++;d.Bytes+=uint64(max(0,bytes));if status==206{d.RangeRequests++};if status==200&&bytes==expected&&r.Context().Err()==nil{d.CompletedFull++}};for date,old:=range s.stats.Days{t,e:=time.Parse("2006-01-02",date);if e==nil&&time.Since(t)>72*time.Hour{old.Addresses=nil}}}
func (s *website)pruneLocked(now time.Time){for date,d:=range s.stats.Days{t,e:=time.Parse("2006-01-02",date);if e!=nil||now.Sub(t)>72*time.Hour{d.Addresses=nil}}}
func (s *website)persist()error{s.mu.Lock();s.pruneLocked(time.Now().UTC());b,e:=json.Marshal(s.stats);s.mu.Unlock();if e!=nil{return e};if e=os.MkdirAll(filepath.Dir(s.statePath),0700);e!=nil{return e};p:=s.statePath+".tmp";f,e:=os.OpenFile(p,os.O_WRONLY|os.O_CREATE|os.O_TRUNC,0600);if e!=nil{return e};_,e=f.Write(b);if e==nil{e=f.Sync()};closeError:=f.Close();if e!=nil{return e};if closeError!=nil{return closeError};return os.Rename(p,s.statePath)}
func jsonResponse(w http.ResponseWriter,status int,v any){w.Header().Set("Content-Type","application/json; charset=utf-8");w.WriteHeader(status);_ = json.NewEncoder(w).Encode(v)}
func (s *website)monitorHandler(w http.ResponseWriter,r *http.Request){if r.Method!="GET"{http.Error(w,"GET required",405);return};token:=strings.TrimPrefix(r.Header.Get("Authorization"),"Bearer ");if !strings.HasPrefix(r.Header.Get("Authorization"),"Bearer ")||subtle.ConstantTimeCompare([]byte(token),s.monitor)!=1{http.Error(w,"Unauthorized",401);return};resources,e:=hostmetrics.Read();s.mu.Lock();if e==nil&&s.cpuTotal>0&&resources.CPUTotal>s.cpuTotal&&resources.CPUIdle>=s.cpuIdle{total,idle:=resources.CPUTotal-s.cpuTotal,resources.CPUIdle-s.cpuIdle;if idle<=total{p:=100*(1-float64(idle)/float64(total));resources.CPUPercent=&p}};if resources!=nil{s.cpuTotal,s.cpuIdle=resources.CPUTotal,resources.CPUIdle};copyDays:=map[string]daily{};for date,d:=range s.stats.Days{copy:=*d;copy.Addresses=nil;copy.ByPlatform=map[string]uint64{};for k,v:=range d.ByPlatform{copy.ByPlatform[k]=v};copyDays[date]=copy};today:=copyDays[time.Now().UTC().Format("2006-01-02")];s.mu.Unlock();jsonResponse(w,200,map[string]any{"at":time.Now().UTC(),"node":"build-host","today":today,"days":copyDays,"resources":resources,"privacy":map[string]any{"raw_ip_stored":false,"pseudonyms_retention_hours":72,"traffic_payload_logged":false,"counts_are_installs":false,"unclean_restart_loss_seconds":15}})}
func (s *website)proxyActivation(w http.ResponseWriter,r *http.Request){kind:=strings.TrimPrefix(r.URL.Path,"/vpn/api/v1/");if kind!="info"&&kind!="challenge"&&kind!="enroll"{http.NotFound(w,r);return};method:="POST";if kind=="info"{method="GET"};if r.Method!=method||r.URL.RawQuery!=""{http.Error(w,"Invalid request",405);return};if origin:=r.Header.Get("Origin");origin!=""&&origin!=publicOrigin{http.Error(w,"Origin rejected",403);return};var body []byte;if method=="POST"{if !strings.HasPrefix(r.Header.Get("Content-Type"),"application/json"){http.Error(w,"JSON required",415);return};var e error;body,e=io.ReadAll(http.MaxBytesReader(w,r.Body,16384));if e!=nil{http.Error(w,"Request too large",413);return}};ctx,cancel:=context.WithTimeout(r.Context(),50*time.Second);defer cancel();request,e:=http.NewRequestWithContext(ctx,method,s.backendURL+"/vpn-api/v1/"+kind,bytes.NewReader(body));if e!=nil{http.Error(w,"Gateway unavailable",503);return};request.Header.Set("Content-Type","application/json");request.Header.Set("Accept","application/json");if origin:=r.Header.Get("Origin");origin!=""{request.Header.Set("Origin",origin)};response,e:=s.client.Do(request);if e!=nil{http.Error(w,"Activation temporarily unavailable",503);return};defer response.Body.Close();if response.StatusCode>=300&&response.StatusCode<400{http.Error(w,"Backend redirect rejected",502);return};out,e:=io.ReadAll(io.LimitReader(response.Body,65537));if e!=nil||len(out)>65536{http.Error(w,"Invalid backend response",502);return};w.Header().Set("Content-Type",response.Header.Get("Content-Type"));if response.StatusCode==429{w.Header().Set("Retry-After","60")};w.WriteHeader(response.StatusCode);_,_=w.Write(out)}
type counterWriter struct{http.ResponseWriter;status int;n int64}
func(w *counterWriter)WriteHeader(status int){if w.status==0{w.status=status};w.ResponseWriter.WriteHeader(status)}
func(w *counterWriter)Write(b []byte)(int,error){if w.status==0{w.status=200};n,e:=w.ResponseWriter.Write(b);w.n+=int64(n);return n,e}
func(s *website)download(w http.ResponseWriter,r *http.Request){if r.Method!="GET"&&r.Method!="HEAD"{http.Error(w,"GET required",405);return};id:=strings.TrimPrefix(r.URL.Path,"/vpn/download/");var asset *releaseAsset;m:=s.manifestSnapshot();for _,a:=range m.Assets{if a.ID==id{copy:=a;asset=&copy;break}};if asset==nil{http.NotFound(w,r);return};p:=filepath.Join(s.dir,asset.File);st,e:=os.Lstat(p);if e!=nil||!st.Mode().IsRegular()||st.Size()!=asset.Size{http.Error(w,"Release unavailable",503);return};f,e:=os.Open(p);if e!=nil{http.Error(w,"Release unavailable",503);return};defer f.Close();w.Header().Set("Content-Disposition",fmt.Sprintf(`attachment; filename="%s"`,asset.File));w.Header().Set("ETag",`"`+asset.SHA256+`"`);w.Header().Set("X-Checksum-SHA256",asset.SHA256);w.Header().Set("Cache-Control","public, max-age=300");cw:=&counterWriter{ResponseWriter:w};http.ServeContent(cw,r,asset.File,st.ModTime(),f);if r.Method=="GET"{s.record(r,false,id,cw.status,cw.n,asset.Size)}}
func(s *website)static(w http.ResponseWriter,r *http.Request){if r.Method!="GET"&&r.Method!="HEAD"{http.Error(w,"GET required",405);return};name:="";switch r.URL.Path{case "/vpn/":name="index.html";case "/vpn/activate":name="activate.html";case "/vpn/assets/site.css":name="site.css";case "/vpn/assets/site.js":name="site.js";case "/vpn/assets/activate.js":name="activate.js";default:http.NotFound(w,r);return};b,e:=assets.ReadFile("static/"+name);if e!=nil{http.NotFound(w,r);return};content:=map[string]string{".html":"text/html; charset=utf-8",".css":"text/css; charset=utf-8",".js":"application/javascript; charset=utf-8"}[filepath.Ext(name)];w.Header().Set("Content-Type",content);if r.Method=="GET"&&name=="index.html"{s.record(r,true,"",200,0,0)};if r.Method=="GET"{_,_=w.Write(b)}}
func(s *website)handler()http.Handler{mux:=http.NewServeMux();mux.HandleFunc("/healthz",func(w http.ResponseWriter,r *http.Request){jsonResponse(w,200,map[string]any{"ok":true,"service":"chameleon-web"})});mux.HandleFunc("/vpn/manifest.json",func(w http.ResponseWriter,r *http.Request){if r.Method!="GET"{http.Error(w,"GET required",405);return};jsonResponse(w,200,s.manifestSnapshot())});mux.HandleFunc("/.well-known/assetlinks.json",func(w http.ResponseWriter,r *http.Request){m:=s.manifestSnapshot();if m.AndroidCertSHA256==""{jsonResponse(w,200,[]any{});return};jsonResponse(w,200,[]any{map[string]any{"relation":[]string{"delegate_permission/common.handle_all_urls"},"target":map[string]any{"namespace":"android_app","package_name":m.AndroidAppID,"sha256_cert_fingerprints":[]string{m.AndroidCertSHA256}}}})});mux.HandleFunc("/vpn/internal/monitor",s.monitorHandler);mux.HandleFunc("/vpn/api/v1/",s.proxyActivation);mux.HandleFunc("/vpn/download/",s.download);mux.HandleFunc("/vpn/",s.static)
 return http.HandlerFunc(func(w http.ResponseWriter,r *http.Request){w.Header().Set("X-Content-Type-Options","nosniff");w.Header().Set("Referrer-Policy","no-referrer");w.Header().Set("X-Frame-Options","DENY");w.Header().Set("Permissions-Policy","camera=(), microphone=(), geolocation=()");w.Header().Set("Cache-Control","no-store");w.Header().Set("Content-Security-Policy","default-src 'none'; script-src 'self'; style-src 'self'; connect-src 'self'; img-src 'self' data:; font-src 'self'; frame-ancestors 'none'; base-uri 'none'; form-action 'none'");mux.ServeHTTP(w,r)})}
func main(){listen:=flag.String("listen","127.0.0.1:8002","loopback only");releaseDir:=flag.String("releases","/srv/chameleon/releases","immutable verified releases");manifestPath:=flag.String("manifest","/etc/chameleon/web-manifest.json","public release manifest");state:=flag.String("state","/var/lib/chameleon-web/statistics.json","private counters");caFile:=flag.String("backend-ca","/etc/chameleon/ru-console-cert.pem","pinned RU public certificate");flag.Parse();log.SetFlags(0);salt,e:=credential("visitor_salt");if e!=nil{log.Fatal("visitor salt unavailable")};token,e:=credential("monitor_token");if e!=nil{log.Fatal("monitor credential unavailable")};ca,e:=os.ReadFile(*caFile);if e!=nil{log.Fatal("RU trust certificate unavailable")};pool:=x509.NewCertPool();if !pool.AppendCertsFromPEM(ca){log.Fatal("RU trust certificate invalid")};s:=&website{dir:*releaseDir,manifestPath:*manifestPath,statePath:*state,salt:salt,monitor:token,backendURL:"https://203.0.113.10:51843",client:&http.Client{Timeout:50*time.Second,Transport:&http.Transport{TLSClientConfig:&tls.Config{RootCAs:pool,ServerName:"ks-admin",MinVersion:tls.VersionTLS12},MaxIdleConnsPerHost:8,ResponseHeaderTimeout:45*time.Second},CheckRedirect:func(*http.Request,[]*http.Request)error{return http.ErrUseLastResponse}},stats:statistics{Version:1,Days:map[string]*daily{}}};if b,e:=os.ReadFile(*state);e==nil{if len(b)>8<<20||json.Unmarshal(b,&s.stats)!=nil||s.stats.Version!=1{log.Fatal("statistics state invalid")};if s.stats.Days==nil{s.stats.Days=map[string]*daily{}}}else if !os.IsNotExist(e){log.Fatal("statistics unavailable")};if e=s.loadManifest();e!=nil{log.Fatal("release manifest validation failed")};ctx,cancel:=signal.NotifyContext(context.Background(),os.Interrupt,syscall.SIGTERM);defer cancel();go func(){tick:=time.NewTicker(15*time.Second);defer tick.Stop();for{select{case <-ctx.Done():return;case <-tick.C:if s.persist()!=nil{log.Print("counter persistence unavailable")};if s.loadManifest()!=nil{log.Print("manifest reload rejected; retaining verified configuration")}}}}();server:=&http.Server{Addr:*listen,Handler:s.handler(),ReadHeaderTimeout:10*time.Second,ReadTimeout:55*time.Second,WriteTimeout:120*time.Second,IdleTimeout:60*time.Second,MaxHeaderBytes:16384};go func(){<-ctx.Done();c,cancel:=context.WithTimeout(context.Background(),10*time.Second);defer cancel();_=server.Shutdown(c)}();if e=server.ListenAndServe();e!=nil&&e!=http.ErrServerClosed{log.Fatal("HTTP server failed")};_ = s.persist()}
